# ASP.NET
# Build and test ASP.NET projects.
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build ASP.NET App'
  jobs:
  - job: BuildJob
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(build.artifactStagingDirectory)'
        ArtifactName: 'drop'
      displayName: 'Publish build artifacts'

- stage: Deploy
  displayName: 'Deploy to Windows VM'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployToVM
    displayName: 'Deploy ASP.NET App'
    environment:
      name: 'my-angular-vm'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'my-angular-vm-ssh'
              sourceFolder: '$(Pipeline.Workspace)/drop'
              contents: '**'
              targetFolder: 'C:/inetpub/wwwroot/aspnet-app'
              overWrite: true